### ISSUE TITLE
fastify support

### ISSUE THREAD

**Issue by rodrigo1991** [mxstbr/passport-magic-login#31]
Please change 
`res.json({
          success: true,
          code: code
        });`

to
`res.send({
          success: true,
          code: code
        });`

to make it work on both express and fastify router

**Comment by hfersu** [comment]
I have encountered this error:
```
TypeError: res.json is not a function
    at /app_path/node_modules/passport-magic-login/src/index.ts:105:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: res.json is not a function
    at /app_path/node_modules/passport-magic-login/src/index.ts:109:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
It occurs right after sending the email with the MagicLink to the user.
I'm not sure if it could be related to this Issue since I'm also using Fastify (with NestJs).

**Comment by J-Sek** [comment]
Example workaround for unpatient people.

```ts
@Post('login')
loginWithLink(@Req() req, @Res() res) {
  this.passwordlessStrategy.send(req, {
    ...res,
    status: (code) => {
      res.statusCode = code;
      return res;
    },
    json: res.send.bind(res),
  });
}
```

The underlying project is based on Nest.js, but hopefully you get the idea. Patch `json()` and `status()`
